version: '3.4'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3100
    ports:
      - "3100:3100"
    expose:
      - 3100
    volumes:
      - db_data:/var/lib/mysql
  redis:                                                                          
    image: redis
    ports:
      - "6379:6379" 
    expose:
      - '6379'
  payment:
    image: payment:latest
    network_mode: host
    depends_on:
      - mysql
    environment:
      REDIS_HOST: 'redis:6379'
      MAIN_PORT: '8082'

    # ports:
    #   - "8081:8080" 
    # expose:
    #   - 8081
  payment2:
    image: payment:latest
    network_mode: host
    depends_on:
      - mysql
    environment:
      REDIS_HOST: 'redis:6379'
      MAIN_PORT: '8081'
    ports:
      - "8082:8080" 
  payment3:
    image: payment:latest
    network_mode: host
    depends_on:
      - mysql
    environment:
      REDIS_HOST: 'redis:6379'
      MAIN_PORT: '8084'
    ports:
      - "8084:8080" 
  # loadbalancer:
  #   image: booking-lb
  #   depends_on:
  #     - booking1
  #     - booking2
  #   ports:
  #     - "8001:80"
  #   expose:
  #     - 8001
volumes:
  db_data:
  rabbitmq_data: