global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'payment-service'
    static_configs:
      - targets: ['localhost:2112']
  - job_name: 'wallet-service'
    static_configs:
      - targets: ['localhost:2111']
