version: '3'
services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always
    expose:
      - '9090'
  
  grafana:
    image: grafana/grafana
    network_mode: host
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always

  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - '9093:9093'
  #   volumes:
  #     - ./alertmanager:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/alertmanager.yml'
  #   restart: always
  