{
 "title": "Example for go",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "5th percentile recharge duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (rate(recharge_wallet_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Average recharge duration over the last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(recharge_wallet_duration_seconds_sum[5m])\r\n  / rate(recharge_wallet_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Total count of wallet recharges over the last 5 minutespanel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(recharge_wallet_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile transaction duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(transaction_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average transaction duration over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(transaction_duration_seconds_sum[5m]) \r\n  / rate(transaction_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total count of transactions over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(transaction_ops_processed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}